# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 243)
        Dialog.setMinimumSize(QtCore.QSize(400, 243))
        Dialog.setMaximumSize(QtCore.QSize(400, 243))
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(280, 10, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 200, 101, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.finlabel_2 = QtWidgets.QLabel(Dialog)
        self.finlabel_2.setGeometry(QtCore.QRect(10, 100, 381, 31))
        self.finlabel_2.setText("")
        self.finlabel_2.setObjectName("finlabel_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 60, 381, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.finlabel = QtWidgets.QLabel(Dialog)
        self.finlabel.setGeometry(QtCore.QRect(10, 200, 161, 31))
        self.finlabel.setText("")
        self.finlabel.setObjectName("finlabel")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 200, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(60, 140, 331, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(Dialog)
        self.progressBar_2.setGeometry(QtCore.QRect(60, 170, 331, 23))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 140, 41, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 41, 21))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Auto_Deconvolution_v6"))
        self.pushButton.setText(_translate("Dialog", "폴더찾기"))
        self.pushButton_2.setText(_translate("Dialog", "시작"))
        self.pushButton_3.setText(_translate("Dialog", "종료"))
        self.label.setText(_translate("Dialog", "TOTAL"))
        self.label_2.setText(_translate("Dialog", "IMAGE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
